# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/engineering-and-design',
                'doc_host': 'https://decherd.github.io',
                'git_url': 'https://github.com/decherd/engineering-and-design',
                'lib_path': 'engineering_and_design'},
  'syms': {'engineering_and_design.core': {'engineering_and_design.core.foo': ('core.html#foo', 'engineering_and_design/core.py')}}}
